### ISSUE TITLE
Can't compile apk with proguard enable

### ISSUE THREAD

**Issue by leajim117** [centic9/poi-on-android#29]
Hi, i want to know how can i compile apk with proguard, thanks in advance.

**Comment by centic9** [comment]
Sorry, I am not an Android specialist, but it seems that proguard is enabled in the build.gradle file under "poitest", also there is a file that defines some rules at https://github.com/centic9/poi-on-android/blob/master/poitest/proguard-rules.pro

Otherwise I think it would be best if you look at official documentation from Google about Android developmenbt and otherwise post your question on stackoverflow as there are many more people with more knowledge about Android development/Build there than I am here.
