### ISSUE TITLE
Unable to build gradle after adding ooxml-shemas

### ISSUE THREAD

**Issue by mtariquekhan** [centic9/poi-on-android#61]
After adding poishadow-all.jar and 
implementation('org.apache.poi:ooxml-schemas:1.0'){
        exclude group: 'org.apache.xmlbeans'
 }
and I got this Error:
Duplicate class org.openxmlformats.schemas.drawingml.x2006.chart.CTAxDataSource found in modules ooxml-schemas-1.0.jar (org.apache.poi:ooxml-schemas:1.0) and poishadow-all.jar (poishadow-all.jar)
Duplicate class org.openxmlformats.schemas.drawingml.x2006.chart.CTAxDataSource$Factory found in modules ooxml-schemas-1.0.jar (org.apache.poi:ooxml-schemas:1.0) and poishadow-all.jar (poishadow-all.jar)

**Comment by LePat** [comment]
If my memory is good, poishadow already provides org.apache.poi, do not include it in your project

**Comment by mtariquekhan** [comment]
I agree but some of the schemas are missing in that jar files. That is why I need to add ooxml-schema as well.

**Comment by centic9** [comment]
Unfortunately LePat is correct, all known required classes are already included and you are causing duplicates this way. 

The only option that I see would be to adjust shading locally for you to include the full set instead of the trimmed down one, however your Android App will likely become much bigger because of this...

**Comment by centic9** [comment]
I think this is nothing that we can fix in the main project itself, please send PRs if you came up with a way to achieve this.
